apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-test-pv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath 
  capacity:
    storage: 50Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: k8s-test-pv
  hostPath:
    path: /home/superg/k8s_pv_test
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
