apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: tourbucket-server
  name: tourbucket-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourbucket-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tourbucket-server
    spec:
      containers:
      - image: localhost:32000/tourbucket-server:latest
        imagePullPolicy: Always
        name: tourbucket-server
        ports:
        - containerPort: 3000 
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: usr/src/app/public/data
          name: tb-pv
      volumes:
      - name: tb-pv
        persistentVolumeClaim:
          claimName: tb-pvc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
